# Generated by Django 5.2.1 on 2025-05-27 22:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название проекта')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='Домен сайта')),
                ('pixel_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Уникальный ID пикселя')),
                ('yandex_metrica_counter_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID счетчика Яндекс.Метрики')),
                ('yandex_metrica_access_token', models.TextField(blank=True, null=True, verbose_name='Токен Яндекс.Метрики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
