# Generated by Django 5.2.1 on 2025-05-28 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время заявки')),
                ('google_analytics_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Analytics ID')),
                ('lead_id', models.CharField(db_index=True, max_length=255, verbose_name='CRM Lead ID')),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='CRM User ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Телефон')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('event_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип события (источник)')),
                ('soft_pull_result', models.TextField(blank=True, null=True, verbose_name='Результат Soft Pull')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления записи')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Заявка из CRM',
                'verbose_name_plural': 'Заявки из CRM',
                'indexes': [models.Index(fields=['project', 'lead_id'], name='crm_data_cr_project_1d63ac_idx'), models.Index(fields=['project', 'user_id'], name='crm_data_cr_project_0b0765_idx'), models.Index(fields=['datetime'], name='crm_data_cr_datetim_c37174_idx')],
            },
        ),
        migrations.CreateModel(
            name='RealConversions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время закрытия сделки')),
                ('order_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='ID заказа')),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='CRM User ID')),
                ('lead_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='CRM Lead ID')),
                ('google_analytics_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Analytics ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Телефон')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ценность сделки')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='UTM и другие данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления записи')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Закрытая сделка',
                'verbose_name_plural': 'Закрытые сделки',
                'indexes': [models.Index(fields=['project', 'order_id'], name='crm_data_re_project_7a0947_idx'), models.Index(fields=['project', 'user_id'], name='crm_data_re_project_45196d_idx'), models.Index(fields=['datetime'], name='crm_data_re_datetim_a6e9e2_idx')],
            },
        ),
    ]
