"""
Django settings for tomi_ai_service project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2e8kej6%hd^o(8=867@9c*wre096qq9fw!(7ytv_0ay%sph%tj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'dev.altsurf.ru']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    # Наши новые приложения
    'users.apps.UsersConfig',
    'projects.apps.ProjectsConfig',
    'pixel_data.apps.PixelDataConfig',
    'crm_data.apps.CrmDataConfig',
    'analytics.apps.AnalyticsConfig',
    # Для API
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tomi_ai_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Настройки CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # Если твой тестовый сайт на React/Vue
    "http://127.0.0.1:8000",
    "http://127.0.0.1:8001", # Локальный сервер Django
    "https://stefcom.ru", # Добавь домены, с которых будут приходить запросы пикселя
    "https://sequoiamusic.ru",
    "https://dev.altsurf.ru",
]
CORS_ALLOW_ALL_ORIGINS = False
WSGI_APPLICATION = 'tomi_ai_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# tomi_ai_service/settings.py

# В самом начале файла settings.py, ДО любых других импортов Django
# Добавь эти строки, если ты используешь PyMySQL
# import pymysql
# pymysql.install_as_MySQLdb()
# (Раскомментируй, если понадобится PyMySQL, но сначала пробуем mysqlclient)


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', # Используем MySQL
        'NAME': 'altsurfdev',            # <-- ВСТАВИТЬ СЮДА СВОЕ ИМЯ БД!
        'USER': 'altsurfdevuser',       # <-- ВСТАВИТЬ СЮДА СВОЕ ИМЯ ПОЛЬЗОВАТЕЛЯ БД!
        'PASSWORD': 'nS1lG8xE0v',            # <-- ВСТАВИТЬ СЮДА СВОЙ ПАРОЛЬ!
        'HOST': 'localhost',                               # <-- ВСТАВИТЬ СЮДА СВОЙ ХОСТ БД (скорее всего, 'localhost')
        'PORT': '3306',                                         # Оставь пустым для дефолтного порта
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # Эта папка будет создана при collectstatic