# Generated by Django 5.2.1 on 2025-05-27 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(db_index=True, max_length=255)),
                ('event_timestamp', models.DateTimeField(auto_now_add=True)),
                ('client_timestamp', models.BigIntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('em', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ph', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('lid', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('uid', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Пиксельное событие',
                'verbose_name_plural': 'Пиксельные события',
                'indexes': [models.Index(fields=['event_name', 'project'], name='pixel_data__event_n_c2ec4a_idx'), models.Index(fields=['event_timestamp'], name='pixel_data__event_t_10975c_idx'), models.Index(fields=['client_id'], name='pixel_data__client__ccd68c_idx')],
            },
        ),
    ]
